<a href="https://colab.research.google.com/github/AnthonyJFeola/DS-Unit-4-Sprint-2-Neural-Networks/blob/main/module1-Intro-to-Neural-Networks/LS_DS_431_Intro_to_NN_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:

*The input layer is the first layer of neurons in a neural network. This layer accepts the initial raw data for further processing by the subsequent layers. The input layer is the very beginning of the workflow of a neural network.*

### Hidden Layer:

*A hidden layer is a layer between the input and output layer that applies weights to the inputs and directs them through an activation function. Hidden layers perform non-linear transformations of input data.*

### Output Layer:

*The output layer is the last layer of neurons that produces given outputs for the neural network.*

### Neuron:

*A neuron is a mathematical function conceived as a model of biological neurons. The neuron receives one or more inputs and sums them to produce an output. Usually each input is separately weighted, and the sum is passed through a non-linear function known as an activation function.*

### Weight:

*Weight is the parameter within a neural network that transforms input data within the network's hidden layers. As an input enters the node, it gets multiplied by a weight value and the resulting output is either observed, or passed to the next layer in the neural network. *

### Activation Function:

*An activation function is a function that is added into a neural network in order to help the network learn complex patterns in the data. It takes in the output signal from the previous neuron and converts it into some form that can be taken as input to the next neuron. The activation function decides whether a neuron should be activated or not by calculating weighted sum and further adding a bias. The purpose of the activation function is to introduce non-linearity into the output of a neuron.*

### Node Map:

*A node map is a low-dimensional (typically two-dimensional), discretized representation of the input space of the training samples, called a map, and is a method to do dimensionality reduction. *

### Perceptron:

*A perceptron is a machine learning algorithm that helps provide classified outcomes for computing. In perceptron, the algorithm takes a set of inputs and returns a set of outputs. One of the defining characteristics of perceptron is that it is not just an iterative set of processes, but an evolving process where the machine learns from data intake over time.*

## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | x3| y|
|----|----|---|---|
| 0  | 0  | 1 |1 |
| 1  | 0  | 1 |1|
| 0  | 1  | 1 |1|
| 1  | 1  | 1 |0|

In [1]:
import pandas as pd
import numpy as np

data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [2]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
  sx = sigmoid(x)
  return sx*(1-sx)

In [3]:
df

x1  x2  y
0   0   0  1
1   1   0  1
2   0   1  1
3   1   1  0

In [4]:
inputs = np.array(

[[0, 0, 1],
[1, 0, 1],
[0, 1, 1],
[1, 1, 1]])

In [5]:
inputs

array([[0, 0, 1],
       [1, 0, 1],
       [0, 1, 1],
       [1, 1, 1]])

In [6]:
correct_outputs = [[i] for i in df['y']]
correct_outputs

[[1], [1], [1], [0]]

In [7]:
weights = np.random.random((3,1))
weights

array([[0.48699212],
       [0.1706065 ],
       [0.12814008]])

In [8]:
weighted_sum = np.dot(inputs, weights)
weighted_sum

array([[0.12814008],
       [0.6151322 ],
       [0.29874658],
       [0.7857387 ]])

In [9]:
activated_outputs = sigmoid(weighted_sum)
activated_outputs

array([[0.53199126],
       [0.64911064],
       [0.57413608],
       [0.68691562]])

In [10]:
error = correct_outputs - activated_outputs
error

array([[ 0.46800874],
       [ 0.35088936],
       [ 0.42586392],
       [-0.68691562]])

In [11]:
adjustments = error*sigmoid_derivative(weighted_sum)
adjustments

array([[ 0.11652321],
       [ 0.07992067],
       [ 0.10412536],
       [-0.14772983]])

In [12]:
weights = weights + np.dot(inputs.T, adjustments)
weights

array([[0.41918297],
       [0.12700204],
       [0.2809795 ]])

In [13]:
# Update our weights 10,000 times - (fingers crossed that this process reduces error)
for iteration in range(10000):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(inputs, weights)
    
    # Activate!
    activated_outputs = sigmoid(weighted_sum)
    
    # Cac error
    error = correct_outputs - activated_outputs
    
    adjustments = error * sigmoid_derivative(weighted_sum)
    
    # Update the Weights
    weights = weights + np.dot(inputs.T, adjustments)
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_outputs)

Weights after training
[[-8.01877582]
 [-8.01877582]
 [12.1146298 ]]
Output after training
[[0.99999452]
 [0.98363003]
 [0.98363003]
 [0.01940043]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [14]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [15]:
feats = list(diabetes)[:-1]

In [17]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

data = []
for feature in feats:
  data.append(list(diabetes[feature]))

data_norm = Normalizer().fit(np.array(data))

data_norm.transform(X)

NameError: ignored

In [19]:
##### Update this Class #####

class Perceptron:
    
    def __init__(self, niter = 10):
        self.niter = niter
    
    def __sigmoid(self, x):
        return None
    
    def __sigmoid_derivative(self, x):
        return None

    def fit(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """

        # weights
        self.weight = np.zeros(1 + X.shape[1])

        # Number of misclassifications
        self.errors = []  # Number of misclassifications

        for i in range(self.niter):
          err = 0
          for xi, target in zip(X, y):
            delta_w = self.rate * (target - self.predict(xi))
            self.weight[1:] += delta_w * xi
            self.weight[0] += delta_w
            err += int(delta_w != 0.0)
          self.errors.append(err)
        return self

    def predict(self, X):
      """Return class label after unit step"""
      return None

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?